services:
  projet-leyenda:
    build: .
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./:/tf/projet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia   
